{{- if eq .Values.global.node_env "production" }}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}-httpproxy
  namespace: governify-{{ .Values.global.infrastructure }}
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
       more_set_headers "Access-Control-Allow-Origin: $http_origin";
spec:
  virtualhost:
    fqdn: registry{{ .Values.global.services_prefix }}{{ .Values.global.dns_suffix }}
    tls:
      secretName: {{ .Values.global.infrastructure }}-certs
  routes:
  - services:
    - name: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}
      port: 80
    loadBalancerPolicy:
      strategy: Cookie
{{- end}}