---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}
  name: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}
  namespace: governify-{{ .Values.global.infrastructure }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: {{ .Values.global.node_env }}
            - name: PORT
              value: {{ if eq .Values.global.node_env "production"}}"80"{{ else }}"5800"{{ end }}
            - name: GOV_INFRASTRUCTURE
              value: {{ .Values.global.gov_infrastructure }}
            - name: INFLUXDB_BIND_ADDRESS
              value: {{ .Values.influx_bind_address | quote }}
                  
          image: governify/director:{{ if eq .Values.global.node_env "production" }}{{ .Chart.AppVersion }}{{ else }}develop{{ end }}
          imagePullPolicy: Always
          name: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}
          ports:
            - containerPort: {{ if eq .Values.global.node_env "production"}}80{{ else }}5800{{ end }}
              protocol: TCP
          resources:
            requests:
              memory: 300Mi
            limits:
              memory: 400Mi
      securityContext: {}
