---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}
  name: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}
  namespace: {{ if .Values.global.namespaceOverride }}{{.Values.global.namespaceOverride}}{{ else }}governify-{{ .Values.global.infrastructure }}{{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}
    spec:
      containers:
        - env:
            - name: INFLUXDB_BIND_ADDRESS
              value: ":{{ .Values.influx_bind_address }}"

          image: influxdb:{{ .Chart.AppVersion }}
          imagePullPolicy: Always
          name: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}
          ports:
            - containerPort: 8086
              protocol: TCP
            - containerPort: {{ .Values.influx_bind_address }}
              name: backup
          volumeMounts:
            - mountPath: /var/lib/influxdb
              name: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}-db-volume
      volumes:
        - name: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}-db-volume
          persistentVolumeClaim:
            claimName: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}