apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}
  name: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}
  namespace: governify-{{ .Values.global.infrastructure }}
spec:
  {{- if eq .Values.global.node_env "development" }}
  type: NodePort
  {{- end }}
  ports:
    - name: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}
      port: 8086
      protocol: TCP
      targetPort: 8086
      {{- if eq .Values.global.node_env "development" }}
      nodePort: 5002
      {{- end }}
  selector:
    app: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}