{{- if eq .Values.global.node_env "production" }}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}-httpproxy
  namespace: governify-{{ .Values.global.infrastructure }}
spec:
  virtualhost:
    fqdn: reporter{{ .Values.global.services_prefix }}{{ .Values.global.dns_suffix }}
    tls:
      secretName: {{ .Values.global.infrastructure }}-certs
  routes:
  - services:
    - name: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}
      port: 80
    loadBalancerPolicy:
      strategy: Cookie
{{- end }}