{{- if eq .Values.global.node_env "production" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.global.infrastructure }}-certs
  namespace: {{ if .Values.global.namespaceOverride }}{{.Values.global.namespaceOverride}}{{ else }}governify-{{ .Values.global.infrastructure }}{{ end }}
spec:
  dnsNames:
    - assets{{ .Values.global.services_prefix }}{{ .Values.global.dns_suffix }}
    - ui{{ .Values.global.services_prefix }}{{ .Values.global.dns_suffix }}
    - dashboard{{ .Values.global.services_prefix }}{{ .Values.global.dns_suffix }}
    - director{{ .Values.global.services_prefix }}{{ .Values.global.dns_suffix }}
    - registry{{ .Values.global.services_prefix }}{{ .Values.global.dns_suffix }}
    - reporter{{ .Values.global.services_prefix }}{{ .Values.global.dns_suffix }}
  issuerRef:
    name: {{ .Values.global.infrastructure }}-letsencrypt
    kind: Issuer
  secretName: {{ .Values.global.infrastructure }}-certs
{{- end }}