apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}
  name: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}
  namespace: {{ if .Values.global.namespaceOverride }}{{.Values.global.namespaceOverride}}{{ else }}governify-{{ .Values.global.infrastructure }}{{ end }}
spec:
  {{- if eq .Values.global.node_env "development" }}
  type: NodePort
  {{- end }}
  ports:
    - name: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}
      port: {{ if eq .Values.global.node_env "production"}}80{{ else }}5500{{ end }}
      protocol: TCP
      targetPort: {{ if eq .Values.global.node_env "production"}}80{{ else }}5500{{ end }}
      {{- if eq .Values.global.node_env "development" }}
      nodePort: 5500
      {{- end }}
  selector:
    app: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}