---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}
  name: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}
  namespace: {{ if .Values.global.namespaceOverride }}{{.Values.global.namespaceOverride}}{{ else }}governify-{{ .Values.global.infrastructure }}{{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: {{ .Values.global.node_env }}
            - name: PORT
              value: {{ if eq .Values.global.node_env "production"}}"80"{{ else }}"5501"{{ end }}
            - name: GOV_INFRASTRUCTURE
              value: {{ .Values.global.gov_infrastructure }}
            {{- if .Values.credentials_elk }}
            - name: CREDENTIALS_ELK
              valueFrom:
                secretKeyRef:
                    name: {{ .Values.global.infrastructure }}-secrets
                    key: CREDENTIALS_ELK
            {{- end }}
                  
          image: governify/collector-dynamic:{{ if eq .Values.global.node_env "production" }}{{ .Chart.AppVersion }}{{ else }}develop{{ end }}
          imagePullPolicy: Always
          name: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}
          ports:
            - containerPort: {{ if eq .Values.global.node_env "production"}}80{{ else }}5501{{ end }}
              protocol: TCP
          resources:
            requests:
              memory: 400Mi
            limits:
              memory: 400Mi
      securityContext: {}
