{{- if eq .Values.global.node_env "production" }}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}-httpproxy
  namespace: {{ if .Values.global.namespaceOverride }}{{.Values.global.namespaceOverride}}{{ else }}governify-{{ .Values.global.infrastructure }}{{ end }}
spec:
  virtualhost:
    fqdn: join{{ .Values.global.services_prefix }}{{ .Values.global.dns_suffix }}
    tls:
      secretName: {{ .Values.global.infrastructure }}-certs
  routes:
  - services:
    - name: {{ .Values.global.infrastructure }}-{{ .Chart.Name }}
      port: 80
    loadBalancerPolicy:
      strategy: Cookie
{{- end }}
