apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.infrastructure }}-secrets
  namespace: {{ if .Values.global.namespaceOverride }}{{.Values.global.namespaceOverride}}{{ else }}governify-{{ .Values.global.infrastructure }}{{ end }}
type: Opaque
stringData:

    # CREDENTIALS (For different services)
    {{- if .Values.global.login_user}}
    LOGIN_USER: {{ .Values.global.login_user }}
    {{- end}}
    {{- if .Values.global.login_password}}
    LOGIN_PASSWORD: {{ .Values.global.login_password }}
    {{- end}}
    {{- if (index .Values "assets-manager").private_key }}
    ASSETS_PRIVATE_KEY: {{ (index .Values "assets-manager").private_key }}
    {{- end}}
    {{- if (index .Values "scope-manager").private_key }}
    SCOPE_PRIVATE_KEY: {{ (index .Values "scope-manager").private_key }}
    {{- end}}
    {{- if (index .Values "scope-manager").key_github }}
    KEY_GITHUB: {{ (index .Values "scope-manager").key_github }}
    {{- end}}
    {{- if (index .Values "scope-manager").key_pivotal }}
    KEY_PIVOTAL: {{ (index .Values "scope-manager").key_pivotal }}
    {{- end}}
    {{- if (index .Values "scope-manager").key_travis_public }}
    KEY_TRAVIS_PUBLIC: {{ (index .Values "scope-manager").key_travis_public }}
    {{- end}}
    {{- if (index .Values "scope-manager").key_travis_private }}
    KEY_TRAVIS_PRIVATE: {{ (index .Values "scope-manager").key_travis_private }}
    {{- end}}
    {{- if (index .Values "scope-manager").key_heroku }}
    KEY_HEROKU: {{ (index .Values "scope-manager").key_heroku }}
    {{- end}}
    {{- if (index .Values "scope-manager").key_codeclimate }}
    KEY_CODECLIMATE: {{ (index .Values "scope-manager").key_codeclimate }}
    {{- end}}
