apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.infrastructure }}-secrets
  namespace: governify-{{ .Values.global.infrastructure }}
type: Opaque
stringData:

    # CREDENTIALS (For different services)
    LOGIN_USER: {{ .Values.login_user }}
    LOGIN_PASSWORD: {{ .Values.login_password }}
    CREDENTIALS_ELK: {{ .Values.credentials_elk}}
