apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.infrastructure }}-secrets
  namespace: governify-{{ .Values.global.infrastructure }}
type: Opaque
stringData:

    # CREDENTIALS (For different services)
    {{- if .Values.global.login_user}}
    LOGIN_USER: {{ .Values.global.login_user }}
    {{- end}}
    {{- if .Values.global.login_password}}
    LOGIN_PASSWORD: {{ .Values.global.login_password }}
    {{- end}}
    {{- if (index .Values "assets-manager").private_key }}
    ASSETS_PRIVATE_KEY: {{ (index .Values "assets-manager").private_key }}
    {{- end}}
